### PR TITLE
ENH add diagram to illustrate scikit-learn API

### LINKED ISSUE #231: Add diagram for pipeline and column transformer
Discuss on mattermost with available CSV from Thomas.
We could make some explanations more intuitive using a diagram of a pipeline and column transformer.

### PR DESCRIPTION
**Pull request by glemaitre**
closes #231

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Did you add the file?

**Comment by glemaitre** [comment]
The file is located here: https://github.com/INRIA/scikit-learn-mooc/blob/master/figures/api_diagram.drawio

**Comment by glemaitre** [comment]
Adding additional information from  @ogrisel:

ok merci, pour info ce fichier peut s'ouvrir avec un editeur open source mieux qu'inkspace pour les diagramme: https://app.diagrams.net/ (anciennement draw.io)

Voici le lien de l'editeur pour ce fichier : https://app.diagrams.net/#HINRIA%2Fscikit-learn-mooc%2Fmaster%2Ffigures%2Fapi_diagram.drawio

**Comment by glemaitre** [comment]
This app allows to automatically commit changes in the repository and to export SVG file in the repository as well.

**Comment by glemaitre** [comment]
I will limit this PR to incorporate the figure and we can always update and commit new figures

**Comment by GaelVaroquaux** [comment]
OK!

**Comment by glemaitre** [comment]
I am merging this PR as a first approximation. We can both improve the figure and the text.

**Pull request merged**
