### PR TITLE
ENH fine tune and glue sequences

### PR DESCRIPTION
**Pull request by glemaitre**
This PR intends to reworks/regroup some sequences and work on the introduction of the sequences.

TODO:

- [x] revert changes in quiz

### CODE REVIEW

**Comment by lesteve** [comment]
Maybe don't touch the quizzs too much because #137 is still ongoing and when it is finished I would like to regenerate all the quizzes in the github from the gitlab ones. If we can avoid annoying merge conflicts that would be great!

**Comment by glemaitre** [comment]
> Maybe don't touch the quizzs too much because #137 is still ongoing and when it is finished I would like to regenerate all the quizzes in the github from the gitlab ones. If we can avoid annoying merge conflicts that would be great!

Yep, I am only touching intro/take away and separate notebooks if needed.

**Comment by lesteve** [comment]
You have some changes in quizzes in this PR not sure whether that was intended

**Comment by glemaitre** [comment]
Ups. I saw that I made a search/replace on the `hyper-parameter` -> `hyperparameter`. But this one could be solved easily after your merge

**Comment by lesteve** [comment]
e.g. https://github.com/INRIA/scikit-learn-mooc/pull/142/files#diff-2527a84874e8952d4cdc2c6d34738b1d3e67013b88dc7015496f3494a2ceef09

I am using github as a chat now ...

**Pull request merged**
