### PR TITLE
ENH Add slides to introduce cross validation

### PR DESCRIPTION
**Pull request by ArturoAmorQ**
Partially addresses #445.

The goal of this slides is to dynamically show the splitting into folds using `KFold` and `SuffleSplit` strategies.
It also works as a motivation of the concept "variability of an estimated generalization performance".
Finally, it encourages "data scientist on the wild" to have good practices for scoring.

### CODE REVIEW

**Review by ogrisel — APPROVED** [review]
LGTM but can you please insert the slides at the expected location of the video in the jupyter book as done for the other videos?

I had to forge the URL to be able to preview the slides to check they were no missing figure files:

https://2425-246063957-gh.circle-artifacts.com/0/jupyter-book/slides/index.html?file=../slides/intro_cross_validation.md#p15

**Comment by ogrisel** [comment]
I think they should be inserted after https://2425-246063957-gh.circle-artifacts.com/0/jupyter-book/python_scripts/02_numerical_pipeline_scaling.html but before the module quizz.

**Comment by ArturoAmorQ** [comment]
> I think they should be inserted after https://2425-246063957-gh.circle-artifacts.com/0/jupyter-book/python_scripts/02_numerical_pipeline_scaling.html but before the module quiz.

The idea is to split the [numerical pipeline scaling notebook](https://inria.github.io/scikit-learn-mooc/python_scripts/02_numerical_pipeline_scaling.html) into two to create a new notebook with only the cross validation, and then insert the video between them.

I am already working on such PR, but I need #477 to be reviewed first to avoid conflicts.

**Comment by ArturoAmorQ** [comment]
> The idea is to split the numerical pipeline scaling notebook into two to create a new notebook with only the cross validation, and then insert the video between them.

This is done in #498. We can either merge that PR first and modify this PR to modify the `_toc` file, or merge this PR and then assign the place to the slides there.

**Pull request merged**
