### PR TITLE
Remove redundant text

### PR DESCRIPTION
**Pull request by PatriOr**
I found that these two paragraphs were a bit redundant and I decided to keep the first.

This is my first pull request and I am happy to contribute to the mooc :)

### CODE REVIEW

**Comment by ArturoAmorQ** [comment]
Thanks for pointing this out @PatriOr. Now that you are working on this notebook, would you mind changing verbs to present mode (avoid future mode) in the whole text?

**Review by ogrisel — APPROVED** [review]
LGTM, this is already a net improvement, let's merge. The update to use the present tense can happen in a follow-up PR.

**Comment by ogrisel** [comment]
Thanks @PatriOr!

**Comment by ArturoAmorQ** [comment]
Thanks @PatriOr and congrats on your first merge!

**Pull request merged**
