### PR TITLE
Add YouTube hyperlinks to existing slides

### PR DESCRIPTION
**Pull request by ArturoAmorQ**
This PR aims to linking the different Youtube videos to their respective slides.

Please notice that the  iframe css in `sklearn_mooc.css` still has to be fixed in order to show the video and the slides at the same time. Do not merge this PR until that is solved.

Side-effect: fixes https://github.com/INRIA/scikit-learn-mooc/issues/75

### CODE REVIEW

**Comment by ogrisel** [comment]
Hum, I think we need to fix the CSS before merging this because now the slides and video iframes cover each other...

**Comment by ArturoAmorQ** [comment]
> Hum, I think we need to fix the CSS before merging this because now the slides and video iframes cover each other...

I agree. I will change to WIP.

**Comment by lesteve** [comment]
(Side-comment since I was wondering about it, this does not affect FUN since they get the slides from `https://inria.github.io/scikit-learn-mooc/slides/?file=<file.md>` and not our JupyterBook .md file.

For example they use https://inria.github.io/scikit-learn-mooc/slides/?file=ml_concepts.md rather than https://inria.github.io/scikit-learn-mooc/ml_concepts/slides.html)

**Comment by ogrisel** [comment]
This should be ready for review.

- I simplified the CSS to make the iframe use 100% of the width while keeping the 4/3 aspect ratio;
- Note that for some reasons, the `width="640px" height="480px"` attributes for the YouTube iframes are needed to get the video preview to render correctly, despite the actual width and height beeing overridden in the CSS;
- This also fixes the button to hide the left-side navigation panel which was annoying @lesteve when teaching live from the jupyterbook.

**Review by glemaitre — APPROVED** [review]
LGTM

**Pull request merged**
