### PR TITLE
feat: Adds license to jupyter-book config

### PR DESCRIPTION
**Pull request by darigovresearch**
Relevant to issue #681

### CODE REVIEW

**Comment by lesteve** [comment]
Thanks for your suggestion, I checked what the [Turing Way book](https://the-turing-way.netlify.app) is doing and it does not mention its license in its footer but only in one of its page, as we already do for this repo.

I would be in favour of not adding the licence to the footer in the but I'll let others pitch in if they have a strong opinion.

**Comment by ArturoAmorQ** [comment]
I am also fine with just mentioning the license on the index, but I am open to adding it if we have a good reason why users would benefit of the increased visibility.

**Comment by darigovresearch** [comment]
@lesteve & @ArturoAmorQ thanks for adding your comments. It is very common to make the license explicit (and more discoverable) in the footer as it encourages people to build on top of your work (such as translations, condensed code etc), submit corrections and code fixes.

**Review by ogrisel — APPROVED** [review]
I think it's a good idea to mention the license in the footer.

**Review by ArturoAmorQ — APPROVED** [review]
Merging, thanks!

**Comment by darigovresearch** [comment]
@ArturoAmorQ thanks for the merge !

**Pull request merged**
